services:
  app:
    build:
      context: .         # agora o contexto é a pasta atual (ellis/)
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app           # mapeia ./ellis para /app no container
